### ISSUE TITLE
make an essential version!!

### ISSUE THREAD

**Issue by LizzyMaybeDev** [1fxe/Resource-Pack-Display#7]
~~modcore 2.0~~ essential got released with sk1er beta mods and rpd still uses modcore so make an essential version for all the essentialers out there

**Comment by 1fxe** [comment]
> ~modcore 2.0~ essential got released with sk1er beta mods and rpd still uses modcore so make an essential version for all the essentialers out there

![Eq2Zrs1XEAA1Lqv](https://user-images.githubusercontent.com/37674069/127757270-f5252888-e536-4a8e-bf54-7b54e00a935d.jpg)
